# Generated by Django 3.2.16 on 2022-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionrecord',
            name='base',
            field=models.IntegerField(default=0),
        ),
    ]
